services:
  - type: web
    name: secure-gig-guardian
    env: docker
    repo: https://github.com/TIRTHANATH20/secure-gig-guardian
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    buildCommand: null
    startCommand: null
