services:
  - type: web
    name: secure-gig-guardian
    env: docker
    repo: https://github.com/ArjunJayakrishnan-codes/secure-gig-guardian
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: ""
      - key: MONGODB_DB
        value: "secure_gig_guardian"
      - key: MONGODB_COLLECTION
        value: "insurance_policies"
      - key: MONGODB_CLAIMS_COLLECTION
        value: "claims"
      - key: SUPABASE_URL
        value: "https://wlapbbvommqeuvbkojzh.supabase.co"
      - key: SUPABASE_ANON_KEY
        value: "sb_publishable_-L2Az9pqH2iUrATyGMIEYQ_afk_fwkS"
      - key: VITE_SUPABASE_ANON_KEY
        value: "sb_publishable_-L2Az9pqH2iUrATyGMIEYQ_afk_fwkS"
